import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }) {
  const { name, profile_image_url, description, username } = data;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <Image src={profile_image_url} height={40} width={40} alt="" />
        <h1 className="text-2xl font-black">{name}</h1>
        <p>{description}</p>
      </main>
    </>
  );
}

export const getStaticProps = async () => {
  const user = "SwapBuilds";
  const headers = {
    Authorization: `Bearer ${process.env.NEXT_PUBLIC_BEARER}`,
  };

  const response = await fetch(
    `https://api.twitter.com/2/users/by/username/${user}?user.fields=description,profile_image_url,created_at,public_metrics,url,verified`,
    { headers }
  );
  const data = await response.json();

  return {
    props: {
      data: data.data,
    },
  };
};
